[package]
name = "iced_blur"
version = "0.1.0"
edition = "2024"
authors = ["Richard Custodio <richardcustodio@pm.me>"]
description = "a blur widget for iced"
license = "MIT"

[workspace]
members = ["examples/*"]

[dependencies]
iced = { git = "https://github.com/derezzedex/iced", rev = "2300281a43d7dffd935b0f07bc2c4c939f794288", features = [
    "wgpu",
    "offscreen",
    "advanced",
] }
bytemuck = { version = "1.0", features = ["derive"] }
