[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/derezzedex/iced", rev = "c79a40f35c45d173c7dec6d8abed16bf7bd2bb88" }
iced_blur = { path = "../../" }
