[package]
name = "counter"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { git = "https://github.com/derezzedex/iced", rev = "668ad0e1b34c54e98adbde6902743bf8b6d1f2b5" }
iced_blur = { path = "../../" }
